name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    # All branches

  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.102"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Testing
        run: dotnet test --filter TestCategory!=DatabaseDependency

      - name: Building
        run: dotnet build --no-restore --configuration Release -consoleloggerparameters:NoSummary
